apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template: # how every pod should behave
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: btabe0914/client # us.gcr.io/ticketing-dev-333405/auth
---
apiVersion: v1
kind: Service # to allow request inside the cluster to access to the pod
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
